### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sahabalam** [Nefcore/CRLFsuite#3]
Traceback (most recent call last):
  File "/usr/local/bin/crlfsuite", line 33, in <module>
    sys.exit(load_entry_point('CRLFsuite==2.0', 'console_scripts', 'crlfsuite')())
  File "/usr/local/bin/crlfsuite", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/CRLFsuite-2.0-py3.10.egg/crlfsuite/__main__.py", line 4, in <module>
    from crlfsuite.core.cli import url, threads, verbose, urls, silent, method, std, cookies, data, user_agent, timeout, verify, read_urls, output_file, s_payloads
ImportError: cannot import name 'verbose' from 'crlfsuite.core.cli' (/usr/local/lib/python3.10/dist-packages/CRLFsuite-2.0-py3.10.egg/crlfsuite/core/cli.py)

**Comment by Raghavd3v** [comment]
Hi @Sahabalam,
Thanks for reporting this issue, The issue has been fixed now.
